### PR TITLE
Add Layout page

### PR DESCRIPTION
**Pull request by peter-garvin**
Reviewed with @mjabbink and made all necessary changes. Mike, would you like to double check everything? only thing left outstanding would be a final review with a copy writer

### CODE REVIEW

**Comment by peter-garvin** [comment]
@alisonjoseph do you know why this page isnt taking the styles from the _layout.scss? It was working on my build before applying the last 100+ updates from master

**Comment by mjabbink** [comment]
@peter-garvin update the tabs into pages under the "Layout" section with chevron. Once that is done and Lori proofs copy this can deploy.

**Comment by mjabbink** [comment]
This can deploy

**Comment by alisonjoseph** [comment]
closing in favor of https://github.com/carbon-design-system/design-language-website/pull/377/

**Comment by mjabbink** [comment]
note this ish
https://github.com/carbon-design-system/design-language-website/issues/381

**Pull request closed without merging**
