### PR TITLE
Add missing charts to charts page

### LINKED ISSUE #900: Add missing chart images to Charts page
https://www.ibm.com/design/language/data-visualization/charts

Synchronize mini chart illustrations with Carbon site.

Carbon

———
IDL

### PR DESCRIPTION
**Pull request by DanaPaslaru**
Add:
- grouped bar horizontal chart
- pie chart 
- stacked bar horizontal chart
- floating bar
- wordcloud
- boxplot
- bullet
- circle pack

closes #900

### CODE REVIEW

**Comment by mjabbink** [comment]
@DanaPaslaru If the preview link is correct there are missing charts.


Screen Shot 2021-05-14 at 7 04 14 PM

**Comment by DanaPaslaru** [comment]
@mjabbink Hi, I'll add these new ones, too. Thanks!

**Review by vpicone — APPROVED** [review]
Looks great! Do you think the Vertical and Horizontal bar charts should be next to each other rather split up at the start and end of the group?
Screen Shot 2021-05-18 at 11 02 26 AM

**Comment by DanaPaslaru** [comment]
@vpicone Hi, I'm waiting for a feedback from Mike, probably we'll remove them in order to be consistent with carbon site, but if we keep the horizontal bar and the grouped horizontal bar, then I think it would be best, indeed, to put them right after their vertical versions. Thanks!

**Comment by vpicone** [comment]
@DanaPaslaru sounds good, just ping me when we're ready

**Comment by vpicone** [comment]
@DanaPaslaru is this still in progress?

**Comment by DanaPaslaru** [comment]
> @DanaPaslaru is this still in progress?

Hi, Vince, I just need circle pack url from carbon to add here, wasn't working this morning, I'll try a bit later. After I'll add the url for circle pack, this page will be ready. Thanks!

**Comment by vpicone** [comment]
closes #900

**Comment by vpicone** [comment]
@DanaPaslaru sounds good! Let's get it merged in!

**Review by aledavila — APPROVED** [review]

**Comment by aledavila** [comment]
@DanaPaslaru @vpicone hey is this ready to merge ?

**Comment by DanaPaslaru** [comment]
@vpicone @mjabbink Hi, I've checked and fixed the broken links, I think this page is ready for deploy. Thanks!

**Comment by mjabbink** [comment]
Awesome. Looks ready to go Cotton Eye Joe!

**Pull request merged**
