### PR TITLE
chore: update theme

### PR DESCRIPTION
**Pull request by vpicone**

### CODE REVIEW

**Comment by vpicone** [comment]
@alisonjoseph looks like it’s working 🤷‍♂

**Comment by alisonjoseph** [comment]
why do you have so many more changes than my new PR? Also, this seems to be missing the package.json update?

**Comment by vpicone** [comment]
When using yarn, it doesn't update package.json unless it changes the semver. Since `1.4.0` still matches `^1.3.5` only the yarn lock gets updated. You gotta use `yarn upgrade-interactive` or `yarn upgrade gatsby-theme-carbon` instead of manually changing the package.json.

**Comment by alisonjoseph** [comment]
That makes sense, but I also like updating the package.json so I can see what version I'm on (more specifically for the theme than any of the other packages)

**Comment by vpicone** [comment]
@alisonjoseph the yarn blog actually recommends [removing the package then adding it back](https://yarnpkg.com/blog/2016/11/24/offline-mirror/#updating-your-package) which would update the package.json and clear out all the unused deps

**Comment by alisonjoseph** [comment]
I usually run `rm -rf .yarn-offline-mirror node_modules && yarn cache clean && yarn install ` 🤷‍♀

**Pull request merged**
