### PR TITLE
docs: pictogram usage images and table updated

### PR DESCRIPTION
**Pull request by conradennis**
made changes to images and table referenced in this issue: https://github.com/carbon-design-system/design-language-website/issues/294

@alisonjoseph @connor-leech

### CODE REVIEW

**Comment by connor-leech** [comment]
@alisonjoseph @vpicone We couldn't get the `<Artboard>` component to work, and I haven't used it yet so I wasn't very helpful.

Any idea what's up?

**Comment by vpicone** [comment]
idk if it works with svg's try a png's and see if you get the same error

**Comment by alisonjoseph** [comment]
We're using it with svgs on the Carbon website (see https://www.carbondesignsystem.com/guidelines/color/overview#accessibility images)

**Comment by alisonjoseph** [comment]
Looks like Art direction is working correctly, you can't replace one image with two, you'll have to coming mobile1/2 into one svg.

**Comment by alisonjoseph** [comment]
is this ready for re-review @conradennis ?

**Comment by conradennis** [comment]
@alisonjoseph yes it's ready

**Comment by alisonjoseph** [comment]
Hmm, not sure its displaying correctly? IS this the expected resuklt at tablet and mobile?
Screen Shot 2019-10-22 at 9 29 40 AM
Screen Shot 2019-10-22 at 9 29 30 AM

**Comment by conradennis** [comment]
mobile should be the first image you posted where the sizes are stacked see below:

Screen Shot 2019-10-22 at 10 34 19 AM

all other screen sizes should be the desktop version:

Screen Shot 2019-10-22 at 10 33 59 AM

also copy in the blurb needs to replace "32px" with "48px"

**Comment by conradennis** [comment]
@alisonjoseph thank you, I really appreciate the help! Everything looks good to me.

The only thing that needs updating now is the copy above the image where it says the minimum size is 32px should be updated so the minimum size is 48px.

**Comment by alisonjoseph** [comment]
Updated to 48px and merged in! Thanks @conradennis

**Pull request merged**
