### PR TITLE
App icon updates

### PR DESCRIPTION
**Pull request by peter-garvin**
Includes new & updated icons along with yml file

### CODE REVIEW

**Comment by peter-garvin** [comment]
@vpicone you know what's going on with the SVG processing failure?

**Comment by peter-garvin** [comment]
Also don't understand the node failure in Vercel. I'm on v14.16.1

**Comment by peter-garvin** [comment]
@vpicone can you please take a look at this? I don't know why its failing. My preview is failing as well, something about the app icon library js files, which I did not edit

Screen Shot 2021-05-13 at 3 41 54 PM

**Comment by peter-garvin** [comment]
@sstrubberg is there a dev who can take a look at this?

**Comment by mjabbink** [comment]
@alisonjoseph and @sstrubberg This is a top priority for the brand team.

**Comment by mjabbink** [comment]
@peter-garvin You need help to resolve the error correct?

**Comment by peter-garvin** [comment]
@mjabbink yessir and thank you!

**Comment by vpicone** [comment]
@peter-garvin 1700 files changed doesn't seem right

**Comment by peter-garvin** [comment]
@vpicone There were two folders with app icons:

src/images/app-icons
src/components/SVGLibraries/icon-files

Alison said the one in images was likely old and the library was pulling from SVGLibraries, so I removed the one in images

see: https://github.com/carbon-design-system/design-language-website/pull/848

**Comment by vpicone** [comment]
@peter-garvin yeah I'm not sure where src/components/SVGLibraries/icon-files came from, maybe try moving back?

**Comment by peter-garvin** [comment]
@vpicone I can put it wherever we think is the best place, but let's make sure theres only one set of images. Does it make more sense in images or SVGLibaries?

**Comment by vpicone** [comment]
> @vpicone I can put it wherever we think is the best place, but let's make sure theres only one set of images. Does it make more sense in images or SVGLibaries?

images

**Comment by peter-garvin** [comment]
@vpicone ok I think this guy is good to go

**Comment by mjabbink** [comment]
Great job all. The new app icons are great see.

**Pull request merged**
