### PR TITLE
update whats-new.mdx

### PR DESCRIPTION
**Pull request by sadekbazaraa**
Closes #

Adding hyperlinks to images along with some text updates and additional urls in body copy

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by vpicone** [comment]
@sadekbazaraa woah...you actually crushed it haha. The links work perfectly.

I added the missing images and the appropriate alt text. It's generally better for the images to live with the page they're being used on. Makes it easier to find rather than digging through the catch-all image directory at the root of the project.

A few minor things:
1. The datavis copy is still the stationary copy, is that just a placeholder?
2. The datavis link is broken, is that getting launched soon or something?
2. Talked with @jeanservaas about the `Updates` text for the color v2 section and swapped it for an `h3`. The label component that was there has type treatment that we don't use elsewhere and isn't a valid list element (you can only use `li`). Generally we want to go from h2→h3→h4

**Comment by sadekbazaraa** [comment]
Nice! Glad I sort of got it @vpicone 

1. I do have data vis copy, it was a mistake not to include. How do I go back now and make updates to the current PR?
2. Data vis is supposed to launch today but may be held up for another couple of days. This page is in preparation for that.
3. Cool, I was wondering what was wrong with that on the site. Noted.

I think I tried to put the images in the src/pages directory but didn't have access. What is the best process for me to upload images? Thanks!

**Comment by vpicone** [comment]
@sadekbazaraa i’m not sure there’s a great way to add images through GitHub. 

To add the copy, you can click the “files changed” tab at the top of this PR, then three dots for the markdown file and then click the edit option. 

When you save, it should have the option “commit to patch-2” selected. That means it’ll commit to the current branch this PR created for you (patch-2).

**Comment by vpicone** [comment]
LGTM just ping when you wanna merge it!

**Comment by sadekbazaraa** [comment]
Thanks @vince. I think I'm slowly getting the hang of this. Connor is gonna walk me through some stuff in a bit too. 

I just made another commit opting for the smaller bold label directly above the list for "Updates". I've got it in a design review on our side and will let you know when we're ready to push.

**Comment by vince** [comment]
Hi @sadekbazaraa, you've summoned the wrong Vince! I'm unsubscribing here, please go ahead and ping the person you actually want to talk with. Thanks!

**Comment by vpicone** [comment]
@sadekbazaraa sounds good!

**Comment by sadekbazaraa** [comment]
@vpicone I'm working on Illustration pages on my local environment and just tried <Title> to see how that might look and I got this (see Complementary vs. Analogous which used an h4)

Screen Shot 2020-03-05 at 2 45 21 PM

**Comment by jnm2377** [comment]
Is this closing https://github.com/carbon-design-system/design-language-website/issues/457 ?

**Comment by sadekbazaraa** [comment]
Yes @jnm2377, those issues are resolved with this PR. We are still catching little typos and final tweaks so not yet ready to merge but getting very close. I expect within in the next 48 hours after we launch the Data visualization pages.

**Comment by vpicone** [comment]
@sadekbazaraa is this ready to go live?

**Comment by sadekbazaraa** [comment]
@vpicone we keep getting close but are trying to align with pages that are right around the corner. We had a meeting yesterday with the idea of pushing this along with Illustration and Data Vis pages on Monday so we can continue to refine and QA this week. I need to add Illustration to this What's New page next...

**Comment by vpicone** [comment]
@sadekbazaraa right on, we can always add on to it in a week, a day, an hour w/e.

**Comment by sstrubberg** [comment]
@sadekbazaraa you ready to merge this bad boy?

**Comment by sadekbazaraa** [comment]
@sstrubberg thanks for checking in. Almost.. just waiting on the Data Vis pages to be live on IDL before merging the What's new page. I think they'll be going live today. I'll follow back up as soon as we're ready.

**Comment by sstrubberg** [comment]
Any updates on this PR?

**Comment by sadekbazaraa** [comment]
@sstrubberg I just fixed a couple of broken links in the Pictograms section. Otherwise, we're waiting for the Data Vis pages to go live before we launch this page.

**Comment by mjabbink** [comment]
@vpicone OK to merge

**Pull request closed without merging**
