### PR TITLE
chore: content updates on pictograms page

### LINKED ISSUE #91: Pictograms page - image, caption & copy updates
- [x] The pictograms in these two do and don't images are no longer in use and should be replaced with the images linked below.

replacement do image: https://ibm.box.com/s/fuztp64lznawh3oaqu05iby17gv6ppfp
replacement don't image: https://ibm.box.com/s/1lpaly4kfob67ac05msm13syrdt6fq90

<hr>

- [x] Update captions

Currently:

Update to:
- Do follow the clearance rule to allow for legibility and touch.
- Don't collapse the pictogram clearance area.

<hr>

- [x] update copy and image to:

New copy: 
Use the default rounded corner setting for all shapes and a consistent corner radius of 2px for round shapes. The 2px radius can be increased by a multiple of two when necessary to make the pictogram’s metaphor clear. Use an additional radius to make the metaphor reflect the real form of the object.

Image replacement for desktop:
06_Corners_1.svg: https://ibm.box.com/s/p5vi5v78xei7i8u3xocumqvqdfc4k43k

Image replacements for mobile:
06_Corners_1-1.svg: https://ibm.box.com/s/0io6jjas04u9pnkcc6iwwejasmlhr9od
06_Corners_1-2.svg: https://ibm.box.com/s/bst5ubkuyctp4lkw9s1kh41u8ppgnf46

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #91

Copy/image updates

### CODE REVIEW

**Comment by jeanservaas** [comment]
All these changes look good but I found one other issue with the way this page is displaying... we could address it here or make another PR?


**Preview link:**

- Colored backgrounds need to bleed, right now you can see white surrounding

- Now that we've made the site background G10, the bullseye image doesn't pop off the background, it's the same color. Maybe use CACACA?

image



**See current IDL:**

- There are no white borders visible around the images as there are in the new preview link

- The existing site background is darker, so the gray 10 background on the bullseye image pops nicely.

image

**Comment by alisonjoseph** [comment]
I can address in this PR 👍

**Comment by alisonjoseph** [comment]
@jeanservaas I updated the image to have the darker background image. The white at the bottom is a theme bug on the do-dont examples. I'm opening a PR over there to fix (its a quick one-liner)

**Comment by jeanservaas** [comment]
gulp don't hate me, can you change that images to have a #e5e5e5 background? I can make the artwork if you need me to. Then we can merge.

image

**Comment by alisonjoseph** [comment]
Just updated! Its an easy update since its an svg, can just do it right in the code

**Pull request merged**
