### PR TITLE
New app icon usage guidance

### PR DESCRIPTION
**Pull request by peter-garvin**
updated usage guidance for app icons (pending design review)

### CODE REVIEW

**Comment by peter-garvin** [comment]
@mjabbink @sadekbazaraa Please review these updates for app icons usage. I've reflected more of the content from UI icons and Pictograms and added in guidance for marketing and merchandise under "Icon vs logo usage". Let me know what you think

https://design-language-website-5dyxmma2x.vercel.app/iconography/app-icons/usage

**Comment by sadekbazaraa** [comment]
Slick @peter-garvin much more comprehensive now and I like having more parity with the other pages. I do think we'll likely want to spell out "verses" instead of having "vs". Joana and Sarah from IT Infrastructure have been working on an app icons section so some of this will also be quite useful for them as well. I haven't gone through every single detail but at first glance this is a great update.

**Comment by peter-garvin** [comment]
@sstrubberg @vpicone These changes are good to go! Please merge if everything looks good on your end

**Comment by mjabbink** [comment]
Looks good @peter-garvin To the glass!

**Comment by mjabbink** [comment]
@vpicone Can be prioritize to get released as soon as possible.

**Comment by sadekbazaraa** [comment]
Rock n' roll fellas!

**Comment by mjabbink** [comment]
:+1: :+1:

**Pull request merged**
