### PR TITLE
fix: 530-2x-grid-missing-poster-image

### LINKED ISSUE #530: [2x Grid] Missing poster image
Missing poster image for divisions of two. Not sure whats happening here, markdown looks correct.
Should be this image: https://github.com/carbon-design-system/design-language-website/blob/master/src/pages/images/divisions-of-two.jpg

Screen Shot 2020-04-28 at 10 03 29 AM
Screen Shot 2020-04-28 at 10 04 34 AM

### PR DESCRIPTION
**Pull request by andreancardona**
closes #530 

# Testing Instructions: 

- [ ] Navigate to deploy preview: https://deploy-preview-538--design-language-website.netlify.app/design/language/2x-grid

- [ ] 2x grid `Divisions of Two`  should now have the image as seen below:
Screen Shot 2020-05-04 at 2 21 04 PM

### CODE REVIEW

**Comment by mjabbink** [comment]
When will this be live? Not seeing it as of yet.

**Comment by mjabbink** [comment]
@vpicone We gotta get this live guys. https://www.ibm.com/design/language/2x-grid/#divisions-of-two

**Comment by vpicone** [comment]
Looks like it got merged 4 days ago, if it’s
Not fixed all the way we can open a new issue. @andreancardona

**Comment by mjabbink** [comment]
I see it now. All good. Took days for it to show up live.

:+1:

**Pull request merged**
