### PR TITLE
expressive pictograms updates

### PR DESCRIPTION
**Pull request by peter-garvin**
Updated guidance for IDL pictograms, including expressive pictograms

**This is a dependency of https://github.com/carbon-design-system/carbon/pull/8213**

Related PRs:
https://github.com/carbon-design-system/carbon-website/pull/2196

https://github.com/carbon-design-system/carbon/pull/8213

Related issues:
https://github.com/carbon-design-system/design-language-website/issues/903

### CODE REVIEW

**Comment by mjabbink** [comment]
Looking good @peter-garvin. Agree with you to remove table and also I think to add a size image starting from 64 might be helpful.

**Comment by mjabbink** [comment]
@peter-garvin Diana made the Adobe illustrator icons available I think so maybe it’s easy to update the ones in the cards on the “Design” page to the latest.

**Comment by peter-garvin** [comment]
@mjabbink Yep I remember her saying something about that a while back, I already pinged her in our bxd issue 👍

**Comment by mjabbink** [comment]
Sweet.

**Comment by mjabbink** [comment]
@peter-garvin the current (on the glass) pictogram card has the right adobe icon.

**Comment by peter-garvin** [comment]
OK everything looks good to go on my end here @vpicone @sstrubberg

**Comment by peter-garvin** [comment]
Whenever we get this reviewed and pushed, let's try to push this PR at the same time:
https://github.com/carbon-design-system/design-language-website/pull/874

**Pull request merged**
