### PR TITLE
Update content in IBM Logos / 8-Bar

### PR DESCRIPTION
**Pull request by DianaStanciulescu**
Update content as discussed in this issue: https://github.ibm.com/brand/design-language/issues/88?email_source=notifications&email_token=AAAW7RSCNVQFBHY434JBRL3RKNI7BA5CNFSM4AFVN3Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOAEQOE6Q#

WIP invision:  https://ibm.invisionapp.com/share/TQNZQ6N3RHP

I will add a comment when this is ready for review, many changes to be made.

### CODE REVIEW

**Comment by vpicone** [comment]
Hey @DianaStanciulescu is this ready to review?

**Comment by DianaStanciulescu** [comment]
ready for review and going live if ok

**Comment by vpicone** [comment]
@mjabbink did you want to check this?

**Comment by mjabbink** [comment]
Is there a staging link?

I noticed a spacing is issue in rebus page. Gatsby issue. I made issue and like 4tg down in brand column. This issue will be the same for the 8-bar page. it’s a mobile Issue

**Comment by vpicone** [comment]
@mjabbink staging is here: https://deploy-preview-494--design-language-website.netlify.app/

We'll merge it once you're cool with it.

**Comment by DianaStanciulescu** [comment]
I need to make an edit, please hold. thanks!

**Comment by DianaStanciulescu** [comment]
@mjabbink  so ok to go live?
preview link: https://deploy-preview-494--design-language-website.netlify.app/design/language/ibm-logos/8-bar

**Comment by mjabbink** [comment]
@DianaStanciulescu @vpicone To the glass my friends.

**Pull request merged**
