### PR TITLE
Update content IBM logos / Rebus

### PR DESCRIPTION
**Pull request by DianaStanciulescu**
Update content as discussed in this issue: https://github.ibm.com/brand/design-language/issues/88?email_source=notifications&email_token=AAAW7RSCNVQFBHY434JBRL3RKNI7BA5CNFSM4AFVN3Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOAEQOE6Q#

WIP invision: https://ibm.invisionapp.com/share/TQNZQ6N3RHP

I will add a comment when this is ready for review, many changes to be made.

### CODE REVIEW

**Comment by vpicone** [comment]
Hey @DianaStanciulescu is this ready to review?

**Comment by DianaStanciulescu** [comment]
@vpicone @mjabbink only last night I got the OL from Lori to integrate a bunch of copy changes, I will make those and submit both logo and rebus for review by the end of the day. thanks!

**Comment by DianaStanciulescu** [comment]
ready for review, it can go live if it's ok

**Comment by mjabbink** [comment]
release this puppy

**Pull request merged**
