### PR TITLE
chore: update homepage images closes #497

### LINKED ISSUE #497: [IDL] Home page - photos fix
url: https://www.ibm.com/design/language/

On the IDL Home page there are a few photos that have some problems:
- the carbon component image needs to have the components smaller in the field
- the desktop photography image with the divers on the beach is wrong, it needs a different crop
- the mobile photography images, wind turbines and divers, have weird crops, I created square crops for mobile, IF the component becomes a square image with card underneath (like the watson XG site) right now it behaves differently, not sure if it's correct

all images mentioned are here:  https://ibm.box.com/s/76653v0l3sxb73rqzgpnr377v7kzfx56

### PR DESCRIPTION
**Pull request by vpicone**
@DianaStanciulescu this is ready for review.

### CODE REVIEW

**Comment by DianaStanciulescu** [comment]
@vpicone is this the correct behavior of the feature card for mobile? On IDL it looks like this:
now


But on Watson and other sites it looks like this:
watson

If the current IDL behavior is correct, I should give you different photography crops, please tell me what size should they be in? (Or would they be any hight I give you, in which case I will save them as 9:16?)

**Comment by vpicone** [comment]
@DianaStanciulescu that component is a carousel, it doesn’t support multiple crops at the moment.

**Comment by vpicone** [comment]
Looks like the carousel is an IDL only deal,I can work on it, but handling multiple images and multiple crops at various breakpoints gets sort of dicey.

**Comment by DianaStanciulescu** [comment]
@vpicone aha, I see. 
In the feature card it looks like there are two versions of the photos, the 16:9, with a corner card that gets bigger as the screen grows smaller, and then the square image, that looks huge on a horizontal mobile, but ok on a normal, vertical mobile screen. 

I guess there is always the solution of having it as a simple feature cards. 

@mjabbink what should be do? do you think it is worth vince's effort to work on the carousel component , gien that this is the only instance where it appears?  or leave as is? or make this a simpe feature card with only one image?

**Comment by vpicone** [comment]
@DianaStanciulescu A third option might be leaving it like this with the aspect ratio and the new crops you provided.

**Comment by DianaStanciulescu** [comment]
@vpicone so square images with their lower right quarter being the button in the corner, like this? I think that would work! @mjabbink ?

new

**Comment by vpicone** [comment]
@DianaStanciulescu I was saying rather than change any aspect ratios/adding new functionality we just update the images to use your new crop (this is what's happening in the preview now).

## old: 
old

## new:
new

**Comment by mjabbink** [comment]
I like the 1:1 if we have to change it but I do like the 1:2. It would be good to have these options so we can have larger vertical images in mobile (when it works).

**Comment by DianaStanciulescu** [comment]
I will make better 1:2 ones for mobile, the square ones can work ok-ish but I can crop them better.
@vince, give me a few minutes.

**Comment by vpicone** [comment]
@DianaStanciulescu @mjabbink I'll make the 1:1 on mobile work, I might have a clever way to get things working.

**Comment by vince** [comment]
I don't think this is the first time I've been accidentally summoned to this project. @vpicone if you would kindly let people know how to correctly identify you, I'd really appreciate it. :)

**Comment by DianaStanciulescu** [comment]
I added the 1:2 images here: https://ibm.box.com/s/76653v0l3sxb73rqzgpnr377v7kzfx56

[so sorry vince! I will make sure I tag the correct vince!]

**Comment by vpicone** [comment]
@DianaStanciulescu the latest build uses 1:1 on mobile and 16:9 on tablet+desktop with the appropriate image sources for each. I believe this was your original intent.

**Comment by mjabbink** [comment]
@vpicone 1:2 is the original intent

**Comment by DianaStanciulescu** [comment]
to clarify - I was asking about 1:1 because I was not sure which is right. I personally also prefer it because the 2:1 is longer than my mobile screen and not seeing the full image is weird to me, but Mike's the boss

**Comment by vpicone** [comment]
@DianaStanciulescu wait so we're just updating the 1:2 images to use the new crops here?

https://github.com/carbon-design-system/design-language-website/pull/500#issuecomment-610426031

**Comment by DianaStanciulescu** [comment]
@vpicone I think so, yes.

**Comment by mjabbink** [comment]
I thought you preferred 1:2. I’m also OZk with 1:1. Do what you like.

**Comment by vpicone** [comment]
@DianaStanciulescu updated

**Comment by DianaStanciulescu** [comment]
mike, we went with 2:1 . looks ok to me!  

(I see old images when I use responsive mode on my laptop, but if I rescale the screen it looks fine, so I am guessing it's a cache thing on my end or something)

**Comment by vpicone** [comment]
@DianaStanciulescu could you explain which images and at which size are showing up unexpected? Try a different browser or incognito mode to test the caching theory.

**Comment by DianaStanciulescu** [comment]
I was talking about the photography carousel images, but I can't replicate the error anymore, so it must have been a glitch on my end.

**Pull request merged**
