### PR TITLE
fix(images): replace broken and outdated images

### LINKED ISSUE #404: Logo page: Missing/broken image
https://www.ibm.com/design/language/ibm-logos/8-bar#alignments

The “logo alignments” image is missing

Screen Shot 2020-01-06 at 9 17 30 PM

### LINKED ISSUE #409: UI icons page: missing images
@mjabbink commented on [Thu Jan 09 2020](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/642)

Missing images found here:
https://www.ibm.com/design/language/iconography/ui-icons/design#strokes

current:

---

@mjabbink commented on [Thu Jan 09 2020](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/642#issuecomment-572572507)

sorry, created this in wrong repo. Should be in IDL.

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #404 
Closes #409 
Ref #390 

#### Changelog

**New**

- ibm logos 8 bar page missing image

**Changed**

- ui icons design page image path 
- pictogram design page mobile images

### CODE REVIEW

**Comment by conradennis** [comment]
pictograms design page looks good on mobile
UI icons design page images under keyshapes section are still not scaling properly on mobile:
Screen Shot 2020-01-14 at 1 33 32 PM

**Comment by conradennis** [comment]
just posted updated uI icon images in issue #390 

> @jnm2377 @vpicone I've been making composite images for mobile when there are two images side by side in desktop. linking to the files below:
> 
> saved the first one at 2x size svg: https://ibm.box.com/s/scblpxifhuntisnpzx984o3mw7nefvtl
> 
> Screen Shot 2020-01-14 at 3 50 16 PM
> 
> composite SVG of the second set: https://ibm.box.com/s/6uc6gwnh8x4p6tw1bz3jof7eathy4lut
> 
> Screen Shot 2020-01-14 at 3 50 22 PM

**Comment by vpicone** [comment]
@conradennis the svg images should be able to scale to the full width as-is. I just pushed a tweak to this pr making sure they are. Before we use new assets can you check and see if the problems been resolved.

**Comment by jnm2377** [comment]
@mjabbink who should be reviewing this PR?

**Comment by mjabbink** [comment]
@jnm2377 looks good. The only thing I noticed now was an image that should be made for mobile. I feel like we lost this during migration @conradennis see below and correct me if I’m wrong but I think this was a vertical stacker in mobile

**Comment by vpicone** [comment]
@conradennis gonna merge this, if you have more
To add at a later date we can knock it out in a different issue/PR

**Comment by mjabbink** [comment]
Merge

**Pull request merged**
