### PR TITLE
chore: issue 507 - updated language list

### LINKED ISSUE #507: [IDL + Plex site] Update language list
Both the IDL and Plex site needs to be updated.

IDL
https://www.ibm.com/design/language/typography/typeface#language-support

Plex
https://www.ibm.com/plex/specs/

Content
[Language.list.zip](https://github.com/carbon-design-system/design-language-website/files/4458944/Language.list.zip)

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #507

### CODE REVIEW

**Comment by andreancardona** [comment]
@vpicone weirdd I'm not seeing that on my end 

https://deploy-preview-514--design-language-website.netlify.com/design/language/typography/typeface/#language-support
Screen Shot 2020-04-13 at 11 40 05 PM

**Comment by sstrubberg** [comment]
The bug appears in FF, not Chrome

**Comment by andreancardona** [comment]
@vpicone @sstrubberg - the bug has been fixed 🤦‍♀️ feel free to test again

**Comment by vpicone** [comment]
@andreancardona wooooo ty!

**Pull request merged**
