### PR TITLE
fix: philosophy video spacing closes #790

### LINKED ISSUE #790: Philosophy > Point of view: Add more space under “Philosophy” video
The typography (including caption/aside) are too close to the feature video. @sadekbazaraa can provide the spacing spec for this situation.

https://www.ibm.com/design/language/philosophy/pov

### PR DESCRIPTION
**Pull request by raven-wills**

### CODE REVIEW

**Review by vpicone — APPROVED** [review]

**Review by sstrubberg — APPROVED** [review]
Thanks @raven-wills !

**Comment by vpicone** [comment]
@sadekbazaraa we good here?

**Comment by sadekbazaraa** [comment]
Perfect, thanks! @vpicone @sstrubberg Should I hit Squash and merge when we get to this point going forward?

**Comment by vpicone** [comment]
@sadekbazaraa in general, I prefer the person who opened the PR merges it just in case they had some final clean up stuff.

**Pull request merged**
