### PR TITLE
Comment out starter kits on Illustration pages

### PR DESCRIPTION
**Pull request by sadekbazaraa**
Need to temporarily remove Illustration starter kit Resource cards for a few more weeks until they become available.

https://www.ibm.com/design/language/illustration/line-style/design#resources
https://www.ibm.com/design/language/illustration/flat-style/design#resources
https://www.ibm.com/design/language/illustration/isometric-style/design#resources

### CODE REVIEW

**Comment by sadekbazaraa** [comment]
@vpicone cool cool, I didn't know about copy/paste from previous versions. I know they're coming soonish and didn't want to have to dig up when we're ready. Deleting makes sense if it's simple enough to resurrect.

**Comment by vpicone** [comment]
@sadekbazaraa yeah let's do that, I can help when it's time to dig them up!

**Comment by sadekbazaraa** [comment]
@vpicone cool. I went ahead and deleted.

**Comment by vpicone** [comment]
@sadekbazaraa nice, maybe create an issue to add them back and ping me when we’re good to go!

**Comment by sadekbazaraa** [comment]
@vpicone just checking in on this. I saw you approved but don't see the changes live?

**Pull request merged**
