### PR TITLE
Typeset pt 2

### LINKED ISSUE #67: Add sticky type set component
Add to Type Specs page

https://www.ibm.com/design/language/elements/type-specs-ui

Should be able to adapt from Carbon website addon component https://github.com/carbon-design-system/carbon-website/tree/master/packages/addons-website/src/components/TypesetStyle

### PR DESCRIPTION
**Pull request by vpicone**
Closes #67

TODO:

- [x] Swap background colors? Looks like the theme is accidentally using gray-10 instead of gray-20. might be a pita if folks have updated images already
- [x] margin bottom to match idl

### CODE REVIEW

**Comment by alisonjoseph** [comment]
It's working!! Looks great 🎉

We need to designers eyes on it though before merging, we might want the bottom shadow that Carbon has? Also confirm the background color behind "Expressive" and "Productive" headings since the main background color has changed. I'm wondering if white background with a border below might work, I'm not loving the darker gray. 🤔 

Screen Shot 2019-06-28 at 10 31 15 AM

**Comment by vpicone** [comment]
@alisonjoseph updated the colors to use the super top secret gray-05, I think it looks nice. 

I started implementing the shadow with intersection observer and then a shadow with some weird position absolute cover for the shadow and then saw the IDL didn't use a shadow at all. It's tough managing the shadow for both the breakpoint thing and also the Expressive/Productive title bars which don't exist in Carbon.

I think we can just match IDL re: shadows for now since this page might get nuked from orbit anyway.

**Comment by vpicone** [comment]
Would definitely like a design checkoff tho

**Comment by vpicone** [comment]
@jeanservaas whenever you got a sec

**Comment by jeanservaas** [comment]
Hey @vpicone 

One thing I noticed is that your type component doesn't have the gray 20 rules between in the condensed -- if you go check out IDL you'll see that the rules between the white areas are darker (they're articulated with a gray 20 (dcdcdc) 1 px rule.

All of our components, resources tiles... everything using the condensed grid has these gray 20 separation rules... I think if you add these, the light, subtle (f8f8f8) color isn't so bad.

image

If you still think it's too light, we can use the G10 hover color (e5e5e5) there -- that's what IDL uses for their background.

image

**Comment by vpicone** [comment]
got a verbal okay from @jeanservaas

**Pull request merged**
