### PR TITLE
Fixes and Sponsor Changes People page

### PR DESCRIPTION
**Pull request by Danilo-Colonheze-IBM**
Closes [Issue 6 from Brand Team](https://github.com/ibm-brand/design-language/issues/6)

Round of changes asked by the sponsor after go live and hot fixes.

#### Changelog

**Changed**

- Fixed download link from static path to complete url to fix inconsistency;
- Changed high-fidelity portraits asset;
- Changed skeleton image from `.png` to `.svg`;
- Implemented ImageGallery in example section.

### CODE REVIEW

**Review by sstrubberg — CHANGES_REQUESTED** [review]
Looks like some of the images have conflicts.

**Comment by Danilo-Colonheze-IBM** [comment]
> Looks like some of the images have conflicts.

I made a new commit changing the image names to have a `-v2` at the end.
The conflict is almost certain because I deleted the files mentioned.
But, since I can't solve the conflicts because I don't have write access,
could you please delete (or accept the deletion of) these 2 files having the conflict?

```
src/pages/illustration/people/images/11_Skeleton-structure.png
src/pages/illustration/people/images/23_DougP_line.png
```

The new images are named `11_Skeleton-structure-v2.svg` and `23_DougP_line-v2.png`.

Thanks for the help on this!

**Comment by aledavila** [comment]
hi @Danilo-Colonheze-IBM I've fixed the conflicts can you just verify that i didn't accidentally modify any of your changes please and that everything looks good! and ill be able to merge after.

@sstrubberg pining for a second review thanks

**Comment by Danilo-Colonheze-IBM** [comment]
> hi @Danilo-Colonheze-IBM I've fixed the conflicts can you just verify that i didn't accidentally modify any of your changes please and that everything looks good! and ill be able to merge after.

@aledavila Your conflict resolving didn't changed any of my fixes.
It's good for merging to me.

Thank you for the help!

**Pull request merged**
