### PR TITLE
App icons add to repo 5

### PR DESCRIPTION
**Pull request by gbrlbrb**
Added a list of APP icons (repo 5) in the IDL library.

Issues:

https://github.ibm.com/brand/App-icons/issues/512 watson code assistant for z

https://github.ibm.com/brand/App-icons/issues/435 db2 - icons already added to repo, check&add metadata

https://github.ibm.com/brand/App-icons/issues/502 watsonx code assistant - icon already added to repo, check&add metadata

https://github.ibm.com/brand/App-icons/issues/479#issuecomment-62796544 saas console

https://github.ibm.com/brand/App-icons/issues/391 watsonx orchestrate - replace icon with updated one

https://github.ibm.com/brand/App-icons/issues/475 medical meetup

https://github.ibm.com/brand/App-icons/issues/473 IBM zPricer

https://github.ibm.com/brand/App-icons/issues/508 IBM Instana

https://github.ibm.com/brand/App-icons/issues/495 IBM Turbonomic

https://github.ibm.com/brand/App-icons/issues/500 IBM zOS

https://github.ibm.com/brand/App-icons/issues/492 add IBM® Event Automation, IBM® Event Endpoint Management, IBM® Event Processing and IBM® Event Streams and remove current IBM Event Streams to available in library

https://github.ibm.com/brand/App-icons/issues/518 Data Product Exchange

https://github.ibm.com/brand/App-icons/issues/506 add IBM Software Support label to available icon

https://github.ibm.com/brand/App-icons/issues/488 AI on Z

https://github.ibm.com/brand/App-icons/issues/377 IBM SkillsBuild

https://github.ibm.com/brand/App-icons/issues/442 zXplore

### CODE REVIEW

**Comment by gbrlbrb** [comment]
Hello @kennylam and @ariellalgilmore 

Trying to update the APP icon library but it doesn't seem to work, can you please help me understand what I am doing wrong? Thank you!

CC @DianaStanciulescu

**Comment by gbrlbrb** [comment]
CC @sstrubberg

**Comment by DianaStanciulescu** [comment]
@alisonjoseph @mattrosno @tay1orjones hi! I have your names from Mike Abbink - can one of you please help us fix the code and publish these updates? We checked it with https://www.yamllint.com/  and it looks correct, no idea why we get this error. We also hope there will be no conflicts with the other open PR since they both affect the same file - with different changes. Thanks!

**Comment by alisonjoseph** [comment]
@DianaStanciulescu The failure is unrelated to your PR, looks like some failing PRs were automerged into the repo somehow. Will take a look at getting those reverted so we can merge this in.

**Comment by DianaStanciulescu** [comment]
@alisonjoseph thanks!

**Comment by gbrlbrb** [comment]
Hello, @alisonjoseph 

Thank you very much for the help, I checked the preview and everything looks great. 

There is one thing though that must be addressed. There is this new section at the end of the page called "null". I saw it in the preview and I thought it's because of a conflict between PR #1278 and this one, but then I checked the live version of IDL and I saw it there as well. I know the issues it's not caused by this PR, but can you fix it by removing the "null" section? 

Otherwise, I think we can go live with this PR. Thanks!

**Comment by alisonjoseph** [comment]
@gbrlbrb not sure where the null section is coming from, I'd open an issue for a dev to take a look at.

**Review by sstrubberg — APPROVED** [review]

**Pull request merged**
