### PR TITLE
What's new - illo kits

### PR DESCRIPTION
**Pull request by DianaStanciulescu**
Add the Illo kits article to the what's new IDL page

### CODE REVIEW

**Comment by mjabbink** [comment]
@DianaStanciulescu Looks good to me but only throw out the question of the accessibility for the white stoke on the touch finger. Minor issue if at all but making note of it.

**Comment by DianaStanciulescu** [comment]
@sstrubberg this is ready to go live! thanks!

**Review by sstrubberg — APPROVED** [review]

**Comment by mjabbink** [comment]
Is there a preview or will just merge automatically today?

**Comment by mjabbink** [comment]
and will this be applied to Carbon site as well? Same issue there.

**Comment by DianaStanciulescu** [comment]
@mjabbink looks like this was merged and already live.

**Comment by mjabbink** [comment]
Sorry. I wrote this in the wrong issue! I’m a dummy.

**Pull request merged**
