### PR TITLE
TEST: layout/composition page

### PR DESCRIPTION
**Pull request by peter-garvin**
do not merge

### CODE REVIEW

**Comment by peter-garvin** [comment]
@alisonjoseph do you know why this preview link says its not found?

**Comment by alisonjoseph** [comment]
https://deploy-preview-303--design-language-website.netlify.com/design/language should work. you need to add /design/language to the preview url. Sorry forgot to let you know we updated it for testing purposes.

**Comment by peter-garvin** [comment]
🙌

**Comment by vpicone** [comment]
@peter-garvin what's up with this? Do you need to keep it as a PR?

**Comment by peter-garvin** [comment]
@vpicone sorry just saw this. I'd like to keep it up just for a short while if thats alright, I wanted to have the preview link generated so I could get feedback from the team. I can close this early this week

**Comment by peter-garvin** [comment]
Closing, opening #344

**Pull request closed without merging**
