### PR TITLE
Feat/update whats new

### PR DESCRIPTION
**Pull request by xylish7**
Closes https://github.ibm.com/brand/strategy/issues/49

#### Changelog

**Changed**

- Iconography contributions image on whats-new page

### CODE REVIEW

**Review by vpicone — CHANGES_REQUESTED** [review]
@xylish7 hmmm, something weird is goin on in mobile; it's not respecting the right padding.

Screen Shot 2020-11-17 at 2 11 24 PM

**Comment by xylish7** [comment]
@vpicone This is weird...I've just changed the file as you can see in my last commit. Nothing to the code. I saw that if I remove the *gridImages* class it will bahave ok, but this is weird.

**Comment by vpicone** [comment]
@xylish7 if the new image has a different aspect ratio that could be the culprit.

**Comment by xylish7** [comment]
@vpicone the old picture was 1920 x 1080 which is 16:9 and the new one is 3840 x 2160 which is also 16:9. So not sure what is the problem. Should I commit without `gridImages` class?

**Comment by vpicone** [comment]
@xylish7 if you think that's the right solution! We don't wanna ship it like this, maybe figure out why that class was added in the first place?

**Comment by xylish7** [comment]
@vpicone I remove the class and also I think I found were the problem was.

The images with `gridImages` class have are wrapped in a link: `[link to App icons library](https://www.ibm.com/design/language/iconography/app-icons/library)`

While the image I modified should not be wrapped in a link so this is why it got that padding on mobile: `Iconography`

If everything is ok, please merge it :)

**Review by jnm2377 — APPROVED** [review]
lgtm

**Review by vpicone — APPROVED** [review]

**Pull request merged**
