### PR TITLE
Add animation pages and illustration usage tabs v3

### PR DESCRIPTION
**Pull request by sadekbazaraa**
The new animation guidance pages will include a new "Animation" dropdown in the left nav with the following: Overview, Classic principles, Tips and techniques

Additionally, there will be net new 'Usage' tab pages for each of the 3 illustrations styles: Line, Flat, Iso.

### CODE REVIEW

**Comment by vpicone** [comment]
I'm good once the images are working per @andreancardona

**Comment by andreancardona** [comment]
@sadekbazaraa hello! just wanted to see if there was any update with this?

**Comment by sadekbazaraa** [comment]
Hi @andreancardona, thanks for checking in. I anticipate another 2-3 weeks before we can pull this across the finish line. There's some dependencies and questions around functionality with videos and lottie files that are captured here: https://github.com/carbon-design-system/design-language-website/issues/559

**Comment by mjabbink** [comment]
@vpicone This is a priority for the brand team. This is ready to roll from our side.

**Comment by vpicone** [comment]
@mjabbink as in the PR is ready to merge? Is there any dev work remaining?

**Comment by sadekbazaraa** [comment]
@vpicone as far as we can tell, everything seems to be working as intended so ready to merge. No dev work needed after @jnm2377 helped out. We can make new issues for anything we discover along the way post merge.

FYI @mjabbink

**Comment by mjabbink** [comment]
Yup. Ok to merge. If anything comes up we’ll make new issues

**Comment by vpicone** [comment]
@sadekbazaraa @mjabbink checking this out today. I need to clean some stuff up; should have it merged in a couple hours.

**Comment by sadekbazaraa** [comment]
Thanks @vpicone — I just posted this issue as well with some spacing issues on mobile.
https://github.com/carbon-design-system/design-language-website/issues/597

**Pull request merged**
