### PR TITLE
fix: 557-chart-anatomy-video-update

### LINKED ISSUE #557: [Data Vis] Missing chart anatomy video on Design/Basics
https://www.ibm.com/design/language/data-visualization/design/basics/#chart-anatomy

Screen Shot 2020-05-28 at 12 57 33 PM

@vpicone @sstrubberg @mjabbink

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #557

### CODE REVIEW

**Comment by vpicone** [comment]
We might wanna use the `GifPlayer` component for this so it has a play/pause

**Comment by andreancardona** [comment]
> We might wanna use the `GifPlayer` component for this so it has a play/pause

Totally agree - updated!

**Comment by jnm2377** [comment]
Looks good! Just a quick question. Is the image gallery part intentional? Since there's only one image, seems like we could just use the gif player without the image gallery, but wasn't sure if that was part of the design.

**Comment by andreancardona** [comment]
> Just a quick question. Is the image gallery part intentional? Since there's only one image, seems like we could just use the gif player without the image gallery, but wasn't sure if that was part of the design.

I thought it was always needed for the GifPlayer component (whoops) - I'll take it out since it's unnecessary code :)

**Comment by andreancardona** [comment]
@jnm2377 @sstrubberg  updated!

**Pull request merged**
