### PR TITLE
fix: add design tab to frontmatter

### LINKED ISSUE #444: Missing `Design` tab on icon and pictogram library pages

### PR DESCRIPTION
**Pull request by vpicone**
closes #444

### CODE REVIEW

**Comment by sstrubberg** [comment]
image

Something is goofy with the NextPrev tiles. I would expect Prev to be the Library and Next to be Usage.

**Comment by vpicone** [comment]
@sstrubberg should be fixed now, nice catch!

**Comment by jnm2377** [comment]
I think the issue already existed: https://github.com/carbon-design-system/gatsby-theme-carbon/issues/730 

I know @vpicone just opened a PR for this, but now that I'm looking into it more I think that PR was just to fix grid alignment.. so maybe we should re-open above issue.

**Comment by jnm2377** [comment]
I would be fine re-opening the other issue since it's a different scope, and merging this PR as is. Unless you wanna tackle fixing it in this PR @vpicone

**Comment by vpicone** [comment]
@jnm2377 I think the bug @sstrubberg is talking about persisting is the mixup on the ui-icons design page. Fixing the title fixed it locally but, netlify might have cached the frontmatter or something for the build.

since this issue was only for adding the tab back, I'll open a seperate one if the next/prev weirdness scott brought up persists.

**Pull request merged**
