### PR TITLE
Add App icons - batch 4

### PR DESCRIPTION
**Pull request by DianaStanciulescu**
add icons from the following issues:

https://github.ibm.com/brand/App-icons/issues/476 AI Control Interface for IBM z/OS 
https://github.ibm.com/brand/App-icons/issues/499 CICS Deployment Assistant 
https://github.ibm.com/brand/App-icons/issues/435 new updated stroke Db2 app icon (upload existing icon but name it unassigned, rename db2 plex icon to unassigned db2)  
https://github.ibm.com/brand/App-icons/issues/314 Websphere 
https://github.ibm.com/brand/App-icons/issues/326 GSA Client 
https://github.ibm.com/brand/App-icons/issues/328 IBM Model Builder for macOS 
https://github.ibm.com/brand/App-icons/issues/341 Cognos dashboard 
https://github.ibm.com/brand/App-icons/issues/347 IBM Cloud® Security and Compliance Center 
https://github.ibm.com/brand/App-icons/issues/348 IBM Z Cloud and Modernization Stack 
https://github.ibm.com/brand/App-icons/issues/370 Power Systems app icons (9 icons) _missing one metadata_ https://github.ibm.com/brand/App-icons/issues/373 IBM CICS Explorer 
https://github.ibm.com/brand/App-icons/issues/382 Cloud PAL 
https://github.ibm.com/brand/App-icons/issues/384 IBM Cloud Logs 
https://github.ibm.com/brand/App-icons/issues/429 Carbon UI builder 
https://github.ibm.com/brand/App-icons/issues/440 z/OS Containers 
https://github.ibm.com/brand/App-icons/issues/441 IBM Storage Ceph 
https://github.ibm.com/brand/App-icons/issues/451 IBM Open Enterprise Foundation for z/OS 
https://github.ibm.com/brand/App-icons/issues/456 Images for VPC 
https://github.ibm.com/brand/App-icons/issues/460 VPC landing zone, VSI on VPC landing zone, Red Hat OpenShift Container Platform on VPC landing zone (3 icons) 
https://github.ibm.com/brand/App-icons/issues/476 AI Control Interface for IBM z/OS 
https://github.ibm.com/brand/App-icons/issues/480 IBM Z Environments for DevSecOps Development https://github.ibm.com/brand/App-icons/issues/484 AIOps Insights
https://github.ibm.com/brand/App-icons/issues/494 IBM StepZen GraphQL Server 
https://github.ibm.com/brand/App-icons/issues/497 Wazi Deploy 
https://github.ibm.com/brand/App-icons/issues/499 CICS Deployment Assistant 
https://github.ibm.com/brand/App-icons/issues/359 devops suite (partially updated previously) (9 icons)
https://github.ibm.com/brand/App-icons/issues/462 rename IBM Cloud Private to IBM z/OS® Cloud Broker and upload the new icon 
https://github.ibm.com/brand/App-icons/issues/133 Rational developer for I replace old icon with updated one
https://github.ibm.com/brand/App-icons/issues/485 ibm cloud HPC
https://github.ibm.com/brand/App-icons/issues/510 watsonx x 4
https://github.ibm.com/brand/App-icons/issues/478 replace hyper protect icons with new ones (small edits)
https://github.ibm.com/brand/App-icons/issues/462 rename IBM Cloud Private to IBM z/OS® Cloud Broker and reupload the icon (small edit)

rename in library (master is correct) change IBM Cloud® Virtual Servers Classic to IBM Cloud® Virtual Servers for Classic
rename IBM® Db2® Mirror for 1 to IBM® Db2® Mirror for I

replace CloudSecretsManager svg (fix display issue)
replace Db2Warehouse svg (fix display issue)

integrate in this PR the changes from https://github.com/carbon-design-system/design-language-website/pull/1201: informed by IBM Legal that the icon used by IBM digital Health pass Wallet was transferred to Merative as a trademark. IBM digital Health Pass Issuer and IBM digital Health Pass Verify were not transferred, so IBM is free to use them elsewhere. They are now marked "unassigned"

integrate in this PR the changes from https://github.com/carbon-design-system/design-language-website/pull/1207

### CODE REVIEW

**Comment by DianaStanciulescu** [comment]
@theiliad @guidari can one of you please take a look and approve this PR? having it live as soon as you can would be great since the update includes the watsonx suite.

@mjabbink FYI :D

**Comment by mjabbink** [comment]
@DianaStanciulescu Db2 warehouse was good. It is Db2 that needs to be replaced.

**Comment by DianaStanciulescu** [comment]
@mjabbink db2 warehouse had an export issue and was replaced to display correctly. 

currently: 
Screenshot 2023-08-25 at 11 58 04

**Comment by mjabbink** [comment]
Ah, I see. Yes. Thank you for reminding me.

**Comment by DianaStanciulescu** [comment]
hi @theiliad please take a look and approve. thanks!

**Review by theiliad — APPROVED** [review]
There really isn't code materials here that I can find to review, so I tried to review the files as well as I can, LGTM

**Comment by DianaStanciulescu** [comment]
@theiliad thanks! true, this is not code per se, but it's a necessary step for this update to go live. Is there anything else needed before this is merged with the master?

**Pull request merged**
