### PR TITLE
Update rewrite.conf

### PR DESCRIPTION
**Pull request by rmathur16**

### CODE REVIEW

**Comment by vpicone** [comment]
@rmathur16 In the future, do you mind creating an issue and then closing it in the PR with `closes #1234` or whatever?

Thanks for the PR!!

**Comment by rmathur16** [comment]
@vpicone Sure next time I'll create an issue first. Quick ques, by when will the above updates (redirects) will reflect on prod?
Thanks.

**Comment by vpicone** [comment]
About 30 min after we merge it

**Comment by rmathur16** [comment]
Hi @vpicone @sstrubberg , I see that my updates have been merged but for some reason I still don’t see the URL’s re-directed to the pages mentioned in the conf file…

Few examples are below:-
Line 27 in rewrite.conf: 
https://www.ibm.com/design/language/elements/motion/ should redirect to https://www.ibm.com/design/language/motion-ui/basics/
Line 28 in rewrite.conf:  https://www.ibm.com/design/language/elements/logos/  should redirect to https://www.ibm.com/design/language/ibm-logos/8-bar/
Please let me know if I’m missing something here. Thanks.

**Comment by vpicone** [comment]
@rmathur16 I think it's because all of your rewrite rules have slashes at the end. Open a PR removing those and we'll redeploy.

**Comment by rmathur16** [comment]
@vpicone should not be because of slashes at the end as all IDL URL's does have slashes at the end. Also in the rewrite.conf file all the prior URL's have slashes at the end. Please correct me if I'm wrong. Thx.

**Comment by vpicone** [comment]
@rmathur16 well that’s weird, because I did it for you and it worked.

**Comment by rmathur16** [comment]
@vpicone All the re-directs are working fine now. Thank you :-)

**Pull request merged**
