### PR TITLE
feat: technical diagrams pages

### PR DESCRIPTION
**Pull request by Palke**
New set of pages for future Infographics subset.

Not ready to merge yet, PR to get preview link.

Will tag once ready. Thanks!

### CODE REVIEW

**Comment by Palke** [comment]
Hi @alisonjoseph this one is ready for review :)

**Comment by alisonjoseph** [comment]
@Palke Do we still need to add these new pages to the left nav?

**Comment by Palke** [comment]
Hi @alisonjoseph these two pages (empty) are just placeholder for the content that was supposed to come and be published together.

Also the pages with content are for now removed from the navigation structure as requested by Sadek and @DianaStanciulescu 

If you have any other question please let me know :)

**Comment by alisonjoseph** [comment]
So which page am I reviewing in this PR?

**Comment by DianaStanciulescu** [comment]
@alisonjoseph - we wanted to go public with an "infographics" section, but since we cannot have a single L2 (technical diagrams) in an L1 (infographics), because the L2 will automatically become an L1, we decided to go live incongnito, and not promote the page until we will have infograms ready to go live too. However, we did not want to keep the page in staging until then because we can share on demand with the handful of people asking for guidance on this topic.

**Comment by Palke** [comment]
@alisonjoseph sorry!

https://design-language-website-git-fork-pa-3e3d52-carbon-design-system.vercel.app/infographics/technical-diagrams/design/
https://design-language-website-git-fork-pa-3e3d52-carbon-design-system.vercel.app/infographics/technical-diagrams/usage

**Review by alisonjoseph — APPROVED** [review]
LGTM from dev standpoint 👍

**Comment by alisonjoseph** [comment]
Are we good to merge this?

**Comment by Palke** [comment]
Fine by me! Thanks :) 

@DianaStanciulescu

**Comment by DianaStanciulescu** [comment]
@alisonjoseph @Palke all good!

**Pull request merged**
