### PR TITLE
Metadata yml file for app icons library

### PR DESCRIPTION
**Pull request by DianaStanciulescu**
Creating the list of app icons and corresponding metadata

### CODE REVIEW

**Comment by vpicone** [comment]
@DianaStanciulescu is this still draft? Are we waiting on something?

**Comment by DianaStanciulescu** [comment]
@vpicone there was only one comment I added in there about one of the app names that peggy was not sure about (row 293), but no, we are not waiting for anything

**Comment by vpicone** [comment]
@DianaStanciulescu cool! so you're okay with me merging this now?

**Comment by DianaStanciulescu** [comment]
@vpicone  yes we are; please take a second look and tell me if I should update anything. we can also check in staging if there are any errors in friendly names or category and test some search terms. thanks!!

**Comment by vpicone** [comment]
@DianaStanciulescu great work! There were some random em dashes instead of hyphens, but we should be mostly good to go now

**Review by sstrubberg — APPROVED** [review]

**Review by vpicone — APPROVED** [review]

**Pull request merged**
