### PR TITLE
Updates to app icons pages

### PR DESCRIPTION
**Pull request by peter-garvin**
@mjabbink @conradennis 
Several updates to all app icons pages

**Design**
- Removed the Monochromatic Icon sections from both Stroke and Fill icon sections and added to Usage tab
- Changed the color swatch images for Stroke app icons (see below). Also altered copy to go with it and added a table for colors outside of the 4 provided.
- Removed a couple do/don'ts that I felt were unnecessary to simplify the page a bit
- Removed the gif from color page under Fill app icon color. Redundant and can be misleading as we only want accessible color combos 

**Usage**
- Removed Background Color section. We dont want to encourage people to use colors other than black and white.
- Added Monochromatic icon section from Design tab

**Production**
- Pulled tables out of the list component due to the changes in list component
- Added submission requirements to the Approval process section

.
.
.
#### New color section for stroke app icons
Removed the left images in favor of the right images. Also added a table to show color combos for gradients outside of the ones provided. Is this good or do we want to discourage the use of other colors? We've talked about opening it up a bit to allow for more

See on the preview link for the copy changes 

Screen Shot 2020-07-21 at 2 40 48 PM

#### Moved Monochromatic icons to Usage tab
This is true for all app icons and it seems more usage than design. no need to repeat twice in design tab
Screen Shot 2020-07-21 at 1 52 51 PM

## REMOVED

We actually do this on purpose because type is very small in app icons
Screen Shot 2020-07-21 at 2 55 10 PM

While true, this is covered in the color page and this section says to use only acceptable 2-color families listed on color page so this is redundant. Trying to simplify the page
Screen Shot 2020-07-21 at 2 55 22 PM

This gif is redundant and includes color values we wouldnt want to use on app icons
Screen Shot 2020-07-21 at 2 55 31 PM

We dont want to encourage people to use colors other than black and white. All app icons are shown on either black and white on the page and in the master file, so I dont know that we need any guidance here
Screen Shot 2020-07-21 at 2 55 43 PM

#### spacing in production tab list images 
I cannot figure out why the spacing here is messed up (Production tab/NativeOS/Android). It is the same markdown as images in the other list sections. I asked Josefina and she didn't know what was going on off-hand. It affects two images only in this one section.

Screen Shot 2020-07-21 at 1 50 05 PM

#### spacing in Design tab under gradient stroke color
This spacing also seems awkward but I think thats just how the spacing is baked into the components here

Screen Shot 2020-07-21 at 1 50 25 PM

### CODE REVIEW

**Comment by vpicone** [comment]
@peter-garvin I took care of your merge conflicts, this looks good to me. Is it ready?

**Comment by peter-garvin** [comment]
@vpicone i'd like to get @mjabbink 's OK on the changes before merging

**Comment by peter-garvin** [comment]
@vpicone Were you able to figure out that image spacing issue?

**Comment by vpicone** [comment]
@peter-garvin we've resolved all the ones I can think of, but which one in particular were you think of?

**Comment by peter-garvin** [comment]
Its a spacing issue thats on the site currently too, where the images in [this section](https://www.ibm.com/design/language/iconography/app-icons/production/#android-app-icons) have no spacing, but other images on the page do even though i think its the same markdown

Screen Shot 2020-07-24 at 9 09 14 AM
Screen Shot 2020-07-24 at 9 09 21 AM

**Comment by vpicone** [comment]
Got it, thanks! I’ll check it out today.

**Comment by peter-garvin** [comment]
@vpicone I have changed the list images as mentioned in slack, and I also replaced the video on usage page with a gif player. Everything should be good to go. Could you check to see why the Vercel deployment failed?

**Comment by peter-garvin** [comment]
@vpicone I have changed the list images as mentioned in slack, and I also replaced the video on usage page with a gif player. Everything should be good to go. Could you check to see why the Vercel deployment failed?

**Comment by vpicone** [comment]
@peter-garvin pushed a change to one of your files, should be good now

**Comment by vpicone** [comment]
@peter-garvin is it good to merge?

**Comment by mjabbink** [comment]
Looking good @Peter-Garvin

**Comment by peter-garvin** [comment]
Good to go!

**Pull request merged**
