### PR TITLE
Add icon action bar

### PR DESCRIPTION
**Pull request by vpicone**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by mjabbink** [comment]
these need to be on the bottom
https://deploy-preview-439--design-language-website.netlify.com

**Comment by vpicone** [comment]
@mjabbink are you referring to the tooltips? @aagonzales had them up top: https://github.com/carbon-design-system/carbon-website/issues/766#issuecomment-585460128

**Comment by mjabbink** [comment]
no, I clicked on this link https://deploy-preview-439--design-language-website.netlify.com and the added functionality is on the top so not sure if this is meant to deploy to IDL this way? It was the last inout in the thread.

Screen Shot 2020-02-17 at 5 26 12 PM

**Comment by vpicone** [comment]
Screen Shot 2020-02-17 at 4 27 39 PM

That link isn't up to date, we're adding tooltips to the library component, IDL will look identical to Carbon when this PR is through.

**Comment by mjabbink** [comment]
ok, just curious as to why not live in both places and only Carbon site.

**Comment by vpicone** [comment]
@mjabbink it'll work out, trust me!

**Pull request merged**
