### PR TITLE
[IDL] Update Resource page + other resource cards

### PR DESCRIPTION
**Pull request by DianaStanciulescu**
Update logo request links / resource cards for the typography, 8-bar, rebus,  and resource page in IDL

### CODE REVIEW

**Comment by DianaStanciulescu** [comment]
@vpicone @sstrubberg this is ready to go live.  a summary of all commits:
- edit and update all resource cards in IDL
- upload new logos used in resource cards in a folder src/images/resource-cards
- relink resource cards to new logos
- delete leftover logos used throughout the pages
- small type edits 
- remove some "import.. image" code from a few pages.

**Comment by DianaStanciulescu** [comment]
@sstrubberg @vpicone can you please take a look at this or and approve it if there are no issues? thanks!

**Comment by vpicone** [comment]
@DianaStanciulescu brilliant work!!! Were you able to spot-check all of the pages that were using these icons? It looks good to me, but it's tough to track all the individual changes.

**Comment by DianaStanciulescu** [comment]
@vpicone I checked every single page multiple times so I surely hope I did not miss anything! there may be unused icon images that I missed and have not deleted, but we could do another image cleanup / organization some other time in another pr.

**Comment by vpicone** [comment]
@DianaStanciulescu would it be possible for you to prioritize that new PR while it's clear in your mind?

It becomes much harder for you or someone else to figure out what's unused once it's merged and time elapses. If you want to make an issue so we can prioritize it that'd be awesome.

**Review by vpicone — APPROVED** [review]

**Pull request merged**
