### PR TITLE
feat: add IBM logo guidelines for strategic partners card on 8-bar page

### PR DESCRIPTION
**Pull request by leonardo-christian-ferreira**
Closes [330](https://github.com/ibm-brand/center/issues/330) (Brand Center Issue)

Third-party logo usage page update with new card.

#### Changelog

**New**

- Additional card on the page named as "IBM logo guidelines for strategic partners" linked to the downloadable PDF.
[IBM_logo_guidelines_strategic_partners_v_1_1.pdf](https://github.com/carbon-design-system/design-language-website/files/11455586/IBM_logo_guidelines_strategic_partners_v_1_1.pdf)

### CODE REVIEW

**Comment by Danilo-Colonheze-IBM** [comment]
Reviewers,
once this PR is approved, please also merge it to master branch.

Thank you!

**Review by emyarod — COMMENTED** [review]
https://www.ibm.com/design/language/files/IBM_logo_guidelines_strategic_partners_v_1_1.pdf

is this link live on the site yet? it seems to be a 404 for me

**Comment by Danilo-Colonheze-IBM** [comment]
@emyarod This PR will make it live.
It will be broken if you try to access the direct link right now, or in the preview link commented on the Brand Org Issue.

Once this code is merged, the pdf will be available through the direct link and the new resource card on the page.

Thank you

**Review by emyarod — APPROVED** [review]
got it, looks good to me!

**Pull request merged**
