### PR TITLE
Feat sketch content updates

### PR DESCRIPTION
**Pull request by leonardo-christian-ferreira**
Closes [331](https://github.com/ibm-brand/center/issues/331) (Brand Center Issue)

Edit on IDL landing page & Resources page

#### Changelog

**New**

- Add new resource card on the resource page named as "Carbon design kits" with the link to the card to be
https://carbondesignsystem.com/designing/kits/sketch/

**Removed**

- The two links at the bottom of the IDL left navigation (`IDL Sketch Library` and `Carbon Sketch libraries`)

### CODE REVIEW

**Comment by tw15egan** [comment]
Does this still need a horizontal rule if there are no links below it (under Help)? 

Screenshot 2023-05-11 at 2 57 49 PM

**Comment by tw15egan** [comment]
@leonardo-christian-ferreira The changes seem to have caused a build failure. Is the component you deleted being imported anywhere?

**Comment by leonardo-christian-ferreira** [comment]
Hi @tw15egan Sorry for the delay on answering your question.
I've checked the project files and I could not find any import of the deleted component. I also ran `yarn build` and it worked with no problems. Could you help me on figuring out what is causing this problem?

**Comment by tw15egan** [comment]
@leonardo-christian-ferreira I'm not sure, I was also able to build and run it locally. I don't have access to the Vercel logs, is there a way to clear the cache and try to redeploy?

**Comment by leonardo-christian-ferreira** [comment]
@tw15egan I am not sure if there is a way of removing cache and try redeploy it. Do you know anyone that have access to Vercel logs that may help us?

**Comment by tay1orjones** [comment]
Just cleared cache and redeployed - this was the error
image

**Comment by leonardo-christian-ferreira** [comment]
Hi @tw15egan 

Since the page has been validated on the Vercel deployment, could this PR br approved?
@tay1orjones thanks for your help here.

Thanks in advance.

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
