### PR TITLE
Gallery page update

### PR DESCRIPTION
**Pull request by Palke**
- Updated gallery page with new visuals and removed dark theme
- Updated shadowed GifPlayer to support real "pause" event for the video elements

### CODE REVIEW

**Comment by Palke** [comment]
Hi @francinelucca could you please look up for me in the Vercel dashboard reason for deployment to fail? I do not have access to it. Thanks a lot!

**Comment by francinelucca** [comment]
Redeployment available here https://design-language-website-5umum30z3-carbon-design-system.vercel.app/

**Comment by Danilo-Colonheze-IBM** [comment]
Hello carbon-design-system team!

Brand team is requiring that this PR (in addition to the [Homepage PR](https://github.com/carbon-design-system/design-language-website/pull/1235) goes live today, Monday July 31st.
Please, approve and merge these two PRs mentioned for this to be possible.

Thank you!
FYI @Katie-A-IBM @leonardo-christian-ferreira

**Review by tw15egan — APPROVED** [review]

**Comment by tw15egan** [comment]
@Danilo-Colonheze-IBM thanks for the ping. Just merged them, should be deployed and live shortly 👍🏻

**Pull request merged**
