### PR TITLE
Upload new app icons

### PR DESCRIPTION
**Pull request by peter-garvin**
Does not include metadata yet, just the icon files

### CODE REVIEW

**Comment by vpicone** [comment]
@peter-garvin for the conflicting files in the list above, were those intentionally updated? Should the new versions take precedent?

**Comment by peter-garvin** [comment]
the newest ones uploaded here are the ones that should go up

**Comment by peter-garvin** [comment]
@vpicone @alisonjoseph I'm now noticing there are two places where there are app icons:

src/images/app-icons
src/components/SVGLibraries/icon-files

I only knew about the first one until now. Which one is the library pulling from? components I assume?

**Comment by alisonjoseph** [comment]
Yes, looks like its pulling from the components folder, with the dark/light folders inside of that. The other folder is likely old/outdated.

**Comment by peter-garvin** [comment]
closing in favor of https://github.com/carbon-design-system/design-language-website/pull/931

**Pull request closed without merging**
