### PR TITLE
fix(leftNav): Adding seperators

### PR DESCRIPTION
**Pull request by sstrubberg**
Closes [#679](https://github.com/carbon-design-system/design-language-website/issues/679)

Could use some direction on the colors of the lines for the landing page.

### CODE REVIEW

**Comment by sadekbazaraa** [comment]
@sstrubberg I didn't see the clustering from the staging link above as outlined here: https://github.com/carbon-design-system/design-language-website/issues/679

**Comment by sstrubberg** [comment]
image

Super weird. I wonder if vercel is acting up. This is my local dev env.

**Comment by sstrubberg** [comment]
> @sstrubberg I didn't see the clustering from the staging link above as outlined here: #679

try now.

**Comment by sadekbazaraa** [comment]
Thanks @sstrubberg I see it live now. The light left nav pages look right where all of the rules are the same color. The dark home page should all be the same as well. The new rules should match the more subtle rule that was already present, like above IDL Library. 

Screen Shot 2020-08-13 at 12 36 11 PM

**Comment by sstrubberg** [comment]
I added a [PR](https://github.com/carbon-design-system/gatsby-theme-carbon/pull/968) to theme which should fix the mismatch between colors on the dividers.

**Comment by mjabbink** [comment]
yes. The line color is too light. Should have stayed the same as it was prior.

**Comment by mjabbink** [comment]
Preview link no worky for me

**Comment by mjabbink** [comment]
Preview link no worky for me

**Comment by vpicone** [comment]
@mjabbink that was fixed upstream in a theme update. Should be live shortly

**Comment by mjabbink** [comment]
Same spacing should apply to Libraries and GitHub section. It’s just another section and does not extra space

**Comment by vpicone** [comment]
@mjabbink so do you want us to remove that space just in IDL? In all theme sites? In all theme sites using top level dividers?

**Comment by mjabbink** [comment]
Just IDL and Future Carbon IA. We will also need to adjust Brand Center in very near future (like next week). Filip can do that if he has IDL to look at.

**Pull request merged**
