### PR TITLE
fixed icon dimensions

### PR DESCRIPTION
**Pull request by greeshmareddyg**
https://github.com/carbon-design-system/design-language-website/issues/311

Fixed the image Icon:

Screen Shot 2019-10-18 at 11 26 57 AM

### CODE REVIEW

**Comment by alisonjoseph** [comment]
+1 to not using important. @vpicone do you know what the difference is here between IDL and Carbon sites.

**Comment by greeshmareddyg** [comment]
the row image styles are overriding the image styles so I had to use the important.

**Comment by vpicone** [comment]
@greeshmareddyg you should first try adding an additional css selector. Maybe try the Card class.

**Comment by greeshmareddyg** [comment]
removed important and fixed the image in no-results resource card. this will fix the problem in other places (icon library) as well.

**Pull request merged**
