### PR TITLE
chore: update theme and fix IDL specific spacing issues

### PR DESCRIPTION
**Pull request by vpicone**
Note: for some videos, there's a small spacing after (making the space slightly larger than 32px). This is unavoidable and necessary so the video renders at the correct aspect ratio.

### CODE REVIEW

**Comment by vpicone** [comment]
@mjabbink @sadekbazaraa this PR brings in spacing fixes from the theme and addresses IDL-specific spacing issues (#613, #600)

**Comment by mjabbink** [comment]
@vpicone Still the extra spacing between header and image in mobile:

Screen Shot 2020-07-17 at 1 56 04 PM

**Comment by mjabbink** [comment]
@vpicone but good in desktop:

Screen Shot 2020-07-17 at 2 00 25 PM

**Comment by vpicone** [comment]
@mjabbink resolved

**Pull request merged**
