### PR TITLE
docs(plex): update plex languages list

### PR DESCRIPTION
**Pull request by theiliad**
Got a list from @mjabbink with more languages that plex seems to support that aren't currently covered on this page.

**I'm only comparing the 2 lists and adding new items**, pls check thoroughly and make sure that these are valid. Mike could be a good resource to verify this

### CODE REVIEW

**Review by aledavila — APPROVED** [review]

**Comment by mjabbink** [comment]
Not sure if it's a preview only issue but the non-Latin typefaces are not previewing Plex.

**Comment by theiliad** [comment]
> Not sure if it's a preview only issue but the non-Latin typefaces are not previewing Plex.
> 
> Actually the non-Latins fonts are not displaying in desktop as well. This may be a Preview thing but double checking.

I don't know if it would be, we're just changing some text here

**Comment by theiliad** [comment]
@mjabbink are we good to merge this?

**Comment by alisonjoseph** [comment]
confirming the fonts not showing up seem to just be happening in previews not live site

**Pull request merged**
