### PR TITLE
Update Footer.js

### LINKED ISSUE #867: remove cookies button and move to footer
Remove the cookies button anchored at the bottom of the page and move “Cookie preferences” like https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/ and www.ibm.com

FYI @sadekbazaraa @jeanservaas the cookies button is so bad I can’t take it. I recommend we follow IBM dot com and Carbon for IBM dot com. They also apply it in the footer for Europe. We probably need a spec or a visual for Aux or we add it as the last item in the footer far left column.

The button in mobile is a nuisance to say the least and overlaps with the feedback buttons.

Privacy
Terms of use
IBM.com
Cookie preference

### PR DESCRIPTION
**Pull request by Palke**
Closes #867

In order to add Cookie preferences button placeholder within the footer full shadowing was required. (https://w3.ibm.com/w3publisher/digital-behavior-data-management/gdpr/cookie-consent-adoption)

This implementation was suggested by Juan Leon.

image

Edited implementation as per: https://w3.ibm.com/w3publisher/ibm-web-standards-external/standards-mandatory/tracking-tagging

### CODE REVIEW

**Comment by Palke** [comment]
@vpicone Hi Vince, is there any way to force deploy to vercel? For some reason I can't get the last commits into work.

Thanks.

**Comment by vpicone** [comment]
Hey @Palke sorry I totally missed this notification. Is the preview not updating?

**Comment by Palke** [comment]
WIP

**Comment by Palke** [comment]
@vpicone hey Vince, thanks for the heads up on the Vercel. This is now ready for your review. Please let me know if any clarification / change is needed. 

Thanks.

**Review by vpicone — APPROVED** [review]
Looks good! Nice use of Gatsby API here.

**Pull request merged**
