### PR TITLE
fix: whitespace on Philosophy/POV page

### LINKED ISSUE #157: Philosophy: line width
@jeanservaas @alisonjoseph 
In mobile: The line width and where words are breaking seems off. Are there hard returns in the text? Some lines extend to right margin and some don’t ever if a word could fit up on the previous line.

A4A58800-1A9A-481A-B99A-432B1B18BB93
89B0FDAF-E281-4405-A65C-126F1F36D54E

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #157

### CODE REVIEW

**Comment by alisonjoseph** [comment]
I think the 1rem spacing is supposed to be there.

**Comment by jeanservaas** [comment]
If this is to close 157, something's still not right here, unless I'm missing something, the left-alignment of the right margin copy (the smaller copy) is off and the widths of those smaller paragraphs are different

The width of the paragraphs starting with "Stand out = stand for" are not as wide as those above.

image

Also the 

— Paul Rand quote attribute doesn't match the sizing on the old IDL but Mike may have let that go?   If so don't worry about it.

**Comment by alisonjoseph** [comment]
Oh I'm an idiot.. I didn't even scroll down. 🤦‍♀ I'll fix

**Comment by alisonjoseph** [comment]
fixed @jeanservaas

**Comment by jeanservaas** [comment]
@alisonjoseph sorry to be a pain on this guy, but there are a couple of discrepancies still. (Disregard if Mike has given you other instructions that I don't know about) — if you're in tomorrow, maybe we can look at this guy in person.

- Looks like IDL actually kills the small paragraphs at mobile

- also, the quote goes full screen, no indent at mobile too

image

- there still seems to be something going on with right padding both at mobile and at desktop; at mobile any paragraph right padding should be killed and the paragraphs should all go full width.

- Looks like there should be a column and gutter distance between the main body and the small paragraphs, the paragraphs near the bottom of the page seem to be following that logic, but the "Design is how we build bonds" paragraph gets much closer than the others to the smaller paragraphs. There should also be a return after the first paragraph, "...alike." 

- also the smaller paragraph line lengths seem shorter in general than they are on IDL.

image

**Comment by alisonjoseph** [comment]
Let's sit down next week and figure this out, I believe we need to make some fixes in the theme first to make this look correct.

**Comment by alisonjoseph** [comment]
blocked by https://github.com/carbon-design-system/gatsby-theme-carbon/pull/350

**Comment by alisonjoseph** [comment]
merging these changes. the spacing fixes are in an upstream PR in the theme, will address anything else in the PR that brings those in.

**Comment by mjabbink** [comment]
@alisonjoseph Should this be closed?

**Comment by alisonjoseph** [comment]
this PR was merged/closed last summer @mjabbink

**Pull request merged**
