### PR TITLE
docs: Fix broken sentence on Philosophy>Principles page

### PR DESCRIPTION
**Pull request by connor-leech**
Correcting broken sentence. Aligning the copy with this issue: https://github.com/carbon-design-system/design-language-website/issues/219

Closes https://github.com/carbon-design-system/design-language-website/issues/477

Related to #502

### CODE REVIEW

**Comment by mjabbink** [comment]
@connor-leech not sure if you can fix the spacing issue under the intro text? @sadekbazaraa can provide spacing spec but my hunch is 60px.

**Comment by mjabbink** [comment]
Sweet!

**Comment by mjabbink** [comment]
Thanks @connor-leech Connor and @alisonjoseph!

**Comment by sadekbazaraa** [comment]
@mjabbink @connor-leech there's a few other spacing issues going on here. It should be 80px below the intro paragraph which is what we usually have after the anchor links before the main content starts. In some cases where we don't have anchor links this creating issues across the board. 

It looks like the main body copy is extending the full column width as well instead of 8 columns minus 32px (2rem) like the main body copy everywhere else. And lastly, the spacing around the rules is off too. Not sure how we fix that for Gatsby as it's creating issues everywhere we have rules and type combined. Not sure where we want to capture these issues. Thoughts?

**Comment by connor-leech** [comment]
@sadekbazaraa @mjabbink Vince fixed the spacing here: https://github.com/carbon-design-system/design-language-website/pull/504

I'd drop any other changes you need made into the discussion there.

**Pull request merged**
