### PR TITLE
[UI icons] Update design.mdx

### PR DESCRIPTION
**Pull request by peter-garvin**
closes https://github.com/carbon-design-system/design-language-website/issues/671

Remove extra return within the Corners section

Screen Shot 2020-07-28 at 9 29 49 AM

Also fixing this duplicate image
Screen Shot 2020-07-28 at 9 45 09 AM

And removing redundant mobile images on the whole page. These images are exactly the same between desktop and mobile, no need for art direction
Screen Shot 2020-07-28 at 9 45 32 AM
Screen Shot 2020-07-28 at 9 46 03 AM

### CODE REVIEW

**Comment by tw15egan** [comment]
#### 📝Changed routes:


| [**…graphy/ui-icons/design**](https://design-language-website-git-peter-garvin-patch-1.carbon-design-system.now.sh/iconography/ui-icons/design) |
|:-:|
|<a href="https://design-language-website-git-peter-garvin-patch-1.carbon-design-system.now.sh/iconography/ui-icons/design">Screenshot of /iconography/ui-icons/design</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/QiuPIw8qIo0QRvEaiS564ny8uiE_.png">(view full size)</a> |







Commit 84297e8b4fdfb97fc4f4bac2b53b22ff8998fc40 (https://design-language-website-git-peter-garvin-patch-1.carbon-design-system.now.sh).

**Comment by peter-garvin** [comment]
@tw15egan I just updated some new changes to this PR, see above

**Comment by peter-garvin** [comment]
@tw15egan Sorry... I think it failed cause I missed a line to delete. let's see if it passes now

**Comment by vpicone** [comment]
@peter-garvin It looks like this was happening because the two images got collapsed to a single line. Do we not want to show a specific image on mobile any more?

**Comment by peter-garvin** [comment]
@vpicone the ones I removed were only the do/dont examples – I double checked the images and they were exactly the same artwork. There are other mobile images on the page outside of the do/donts that are good to keep

**Pull request merged**
