### PR TITLE
App icon gallery

### LINKED ISSUE #512: [IDL] Iconography > App icons > Gallery
Create a new Gallery tab in the App icons page:

App icon library

from Peter Garvin:
master here: https://github.ibm.com/brand/App-icons/raw/master/App_Icon_Master.ai
all icons SVG and uploaded to the repo here:
https://github.ibm.com/brand/App-icons/tree/master/svg

sketch file here: https://ibm.box.com/s/yoni7ot52baszyczgouoe7sp5s86xrtu

### PR DESCRIPTION
**Pull request by vpicone**
Closes #512

Adds App Icon library

/iconography/app-icons/library

### CODE REVIEW

**Comment by vpicone** [comment]
@peter-garvin @DianaStanciulescu I uncovered some issues with filenames/icon names. I was able to resolve most, but I'm missing SVG files for the following:

### Missing
- DataCollectionTool
- 007
- 046
- 047
- 053
- 055
- 058
- 066
- 098
- 112

### PNG instead of SVG
- 132

**Comment by mjabbink** [comment]
@sadekbazaraa @peter-garvin Icons are maybe too big. Ether same percentage as UI icons or a but larger but these seem a bit large.

**Comment by peter-garvin** [comment]
@mjabbink this would be a @DianaStanciulescu question as to the intent on icon size and how many across. see https://github.ibm.com/brand/design-language/issues/167

**Comment by mjabbink** [comment]
@peter-garvin @DianaStanciulescu The designs have show 4 across and that seems to be the intent. It’s the right intent to me versus using 6 across. Not sure where 5 came from but needs to be updated.

**Comment by mjabbink** [comment]
I see it’s been updated already. Much better.

**Comment by peter-garvin** [comment]
API connect should be in fill category
Screen Shot 2020-09-23 at 3 06 29 PM

**Comment by vpicone** [comment]
@peter-garvin fixed

**Comment by mjabbink** [comment]
in ”Fill” selection one of the “Stroke” ones show up (IBM API connect).

Screen Shot 2020-09-23 at 9 28 02 PM

**Comment by mjabbink** [comment]
oh shit. I see @peter-garvin already mentioned.

**Comment by mjabbink** [comment]
@peter-garvin I think the type in darker theme could be darker. It’s very high contrast.

**Comment by mjabbink** [comment]
@vpicone @peter-garvin in mobile I wonder if the two drop downs should be side by side. The content is short enough to support this layout.

**Comment by vpicone** [comment]
@mjabbink swapped the tokens for `text-02` (secondary text) for the white and g100 themes respectively. Dropdowns sorted.

**Comment by mjabbink** [comment]
in Fill filter the stroke bugger still makes his appearance.

Screen Shot 2020-09-23 at 9 28 02 PM

In stroke filter the fill bugger still makes her appearance.

Screen Shot 2020-09-24 at 3 16 29 AM

**Comment by mjabbink** [comment]
also found this rogue Fill in Stroke Category (IBM Cognos® Analytics for Mobile)

Screen Shot 2020-09-24 at 12 26 02 PM

**Comment by vpicone** [comment]
@mjabbink @DianaStanciulescu fixed. 

We good to merge? Can always tweak metadata issues in a new PR.

**Comment by mjabbink** [comment]
@vpicone To the glass!

**Pull request merged**
